# Generated by Django 3.2.8 on 2021-10-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('massage', models.TextField()),
                ('date_add', models.DateTimeField(verbose_name='date published')),
                ('public', models.BooleanField(default=False)),
            ],
        ),
    ]
